// Golden fixture self-check: replays the committed Rust golden fixtures
// (`crates/athria-core/tests/fixtures`, generated by `scripts/core-golden.ts`)
// through the TypeScript core and requires the stored expectations to match.
//
// This closes the compatibility loop in both directions: if the TypeScript
// core changes behavior without regenerating the fixtures, `bun run test`
// fails here, and `cargo test -p athria-core` fails on the Rust side until the
// regeneration is committed.
import { readdirSync, readFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import {
  calculateHeartRateZones,
  calculateTrainingMetrics,
  estimateOneRepMax,
  evaluateDoubleProgression,
  evaluateRpeAutoregulation,
  expandSchedule,
  stableHash,
  validatePlan,
} from "./index";

const fixturesDir = resolve(dirname(fileURLToPath(import.meta.url)), "../../..", "crates", "athria-core", "tests", "fixtures");

function run(kind: string, input: Record<string, unknown>): unknown {
  switch (kind) {
    case "schedule":
      return expandSchedule(input as never);
    case "one_rep_max":
      return estimateOneRepMax(input.load as number, input.reps as number, input.unit as never);
    case "heart_rate_zones":
      return calculateHeartRateZones(input.maxHeartRate as number);
    case "training_metrics":
      return calculateTrainingMetrics(input.sessions as never);
    case "double_progression":
      return evaluateDoubleProgression(input as never);
    case "rpe_autoregulation":
      return evaluateRpeAutoregulation(input as never);
    case "stable_hash":
      return stableHash(input.value);
    case "validate_plan":
      return validatePlan(input.profile as never, input.draft as never, new Date(input.now as string));
    default:
      throw new Error(`unknown fixture kind \`${kind}\``);
  }
}

describe("golden fixtures match the TypeScript core", () => {
  const files = readdirSync(fixturesDir).filter((file) => file.endsWith(".json")).sort();

  it("covers every fixture kind", () => {
    const kinds = new Set(files.map((file) => file.split(".")[0]));
    expect([...kinds].sort()).toEqual(["double_progression", "heart_rate_zones", "one_rep_max", "rpe_autoregulation", "schedule", "stable_hash", "training_metrics", "validate_plan"]);
  });

  it("replays all fixtures without drift", () => {
    const failures: string[] = [];
    for (const file of files) {
      const fixture = JSON.parse(readFileSync(join(fixturesDir, file), "utf8")) as { kind: string; name: string; input: Record<string, unknown>; expected?: unknown; error?: string };
      try {
        const actual = JSON.parse(JSON.stringify(run(fixture.kind, fixture.input))) as unknown;
        if (fixture.error !== undefined) failures.push(`${fixture.kind} ${fixture.name}: expected the core to throw ${JSON.stringify(fixture.error)}`);
        else expect(actual).toEqual(fixture.expected);
      } catch (error) {
        if (fixture.error === undefined || (error instanceof Error ? error.message : String(error)) !== fixture.error) {
          failures.push(`${fixture.kind} ${fixture.name}: ${error instanceof Error ? error.message : String(error)}`);
        }
      }
    }
    expect(failures).toEqual([]);
    expect(files.length).toBeGreaterThan(0);
  });
});
