//! Fixture generated by scripts/skill-release.mjs with a public TEST key.
//! Locks down JS -> Rust ZIP, tree identity, envelope and signature compatibility.
use athria_skills::updates::{verify_index, extract_package};
use base64::{Engine, engine::general_purpose::STANDARD};

#[test]
fn node_release_verifies_and_extracts_in_rust() {
    let fixture: serde_json::Value = serde_json::from_str(include_str!("fixtures/node-release.json")).unwrap();
    let index = verify_index(&STANDARD.decode(fixture["envelope"].as_str().unwrap()).unwrap(), fixture["publicKey"].as_str().unwrap()).unwrap();
    let root = std::env::temp_dir().join(format!("athria-node-release-{}", std::process::id()));
    if root.exists() { std::fs::remove_dir_all(&root).unwrap(); }
    extract_package(&STANDARD.decode(fixture["archive"].as_str().unwrap()).unwrap(), &index.packages[0], &root).unwrap();
    assert_eq!(std::fs::read_to_string(root.join("athria-coach/references/guide.md")).unwrap(), "guide");
    std::fs::remove_dir_all(root).unwrap();
}
