import { TEMPLATE_CATALOG_VERSION, type BuiltinSessionTemplate, type SessionTemplate } from "@athria/schemas";

const v = (key: string, required = true, identityConstraint?: { min?: number; max?: number; unit: "repetitions" | "sets" | "seconds" | "minutes" | "meters" | "kilometers" | "rpe" | "watts" | "bpm" }) => ({ key, required, ...(identityConstraint ? { identityConstraint } : {}) });
const builtin = (template: SessionTemplate): BuiltinSessionTemplate => ({ ...template, origin: "builtin", catalogVersion: TEMPLATE_CATALOG_VERSION } as BuiltinSessionTemplate);
const block = (id: string, name: string, role: string, variables: ReturnType<typeof v>[], required = true) => ({ id, name, role, required, variables });

export const builtinSessionTemplates: BuiltinSessionTemplate[] = [
  builtin({ id: "builtin.easy-run", name: "Easy Run", intent: "Build or maintain low-intensity aerobic capacity.", domain: "endurance", commonUseCases: ["Aerobic base", "Recovery running"], notes: "Keep the structure easy; the Weekly Session owns the actual duration and intensity.", structure: { kind: "endurance", blocks: [block("warm-up", "Easy warm-up", "warm_up", [v("duration")]), block("steady", "Continuous easy running", "steady", [v("duration"), v("distance", false), v("rpe", false, { min: 2, max: 4, unit: "rpe" }), v("talk_test", false), v("strides", false)]), block("cool-down", "Easy cooldown", "cool_down", [v("duration")])] } } as SessionTemplate),
  builtin({ id: "builtin.intervals", name: "Intervals", intent: "Develop high-aerobic or event-specific capacity.", domain: "endurance", commonUseCases: ["Aerobic power", "Race-specific work"], notes: "Work and recovery dose are selected per week.", structure: { kind: "endurance", blocks: [block("warm-up", "Warm-up", "warm_up", [v("duration")]), block("repeats", "Repeated work and recovery", "repeat_work_recovery", [v("repetitions"), v("duration", false), v("distance", false), v("pace", false), v("heart_rate_zone", false), v("power", false), v("rpe", false), v("recovery_mode")]), block("cool-down", "Cooldown", "cool_down", [v("duration")])] } } as SessionTemplate),
  builtin({ id: "builtin.long-run", name: "Long Run", intent: "Develop aerobic endurance and durable time on feet.", domain: "endurance", commonUseCases: ["Endurance base", "Event preparation"], notes: "A progressive finish is optional.", structure: { kind: "endurance", blocks: [block("easy-start", "Easy start", "warm_up", [v("duration")]), block("endurance", "Continuous endurance", "steady", [v("duration"), v("distance", false), v("terrain", false), v("rpe", false), v("talk_test", false)]), block("finish", "Optional progressive finish", "steady", [v("duration"), v("pace", false), v("rpe", false)], false)] } } as SessionTemplate),
  builtin({ id: "builtin.lower-strength-a", name: "Lower Strength A", intent: "Develop or maintain lower-body strength.", domain: "strength", commonUseCases: ["General strength", "Athletic support"], notes: "Exercise choice and dose belong to the Weekly Session.", structure: { kind: "strength", slots: [
    { id: "squat", name: "Squat pattern", role: "primary", required: true, movementPatternIds: ["squat"], targetMuscleIds: ["quadriceps", "gluteus_maximus"], matchPolicy: "any", variables: [v("exercise_selection"), v("sets"), v("repetitions"), v("load", false), v("rpe", false), v("rest", false)] },
    { id: "hinge", name: "Hinge pattern", role: "secondary", required: true, movementPatternIds: ["hinge"], targetMuscleIds: ["hamstrings", "gluteus_maximus"], matchPolicy: "any", variables: [v("exercise_selection"), v("sets"), v("repetitions"), v("load", false), v("rpe", false), v("rest", false)] },
    { id: "unilateral", name: "Unilateral lower body", role: "accessory", required: true, movementPatternIds: ["lunge", "step"], targetMuscleIds: ["quadriceps", "glutes"], matchPolicy: "any", variables: [v("exercise_selection"), v("sets"), v("repetitions"), v("alternatives", false)] },
    { id: "hip-stability", name: "Hip stability", role: "accessory", required: false, movementPatternIds: ["hip_abduction"], targetMuscleIds: ["gluteus_medius", "gluteus_minimus"], matchPolicy: "any", variables: [v("exercise_selection"), v("sets"), v("repetitions")] },
    { id: "trunk", name: "Trunk stability", role: "trunk", required: true, movementPatternIds: ["anti_rotation", "anti_extension", "trunk_extension"], targetMuscleIds: ["core"], matchPolicy: "any", variables: [v("exercise_selection"), v("sets"), v("repetitions", false), v("duration", false)] },
  ] } } as SessionTemplate),
  builtin({ id: "builtin.upper-strength-a", name: "Upper Strength A", intent: "Develop or maintain balanced upper-body pushing and pulling strength.", domain: "strength", commonUseCases: ["General strength", "Upper-body maintenance"], notes: "Use the movement slots to preserve balance while varying exercises.", structure: { kind: "strength", slots: [
    { id: "horizontal-push", name: "Horizontal push", role: "primary", required: true, movementPatternIds: ["horizontal_push"], targetMuscleIds: ["chest"], matchPolicy: "any", variables: [v("exercise_selection"), v("sets"), v("repetitions"), v("load", false), v("rpe", false)] },
    { id: "horizontal-pull", name: "Horizontal pull", role: "primary", required: true, movementPatternIds: ["horizontal_pull"], targetMuscleIds: ["back"], matchPolicy: "any", variables: [v("exercise_selection"), v("sets"), v("repetitions"), v("load", false), v("rpe", false)] },
    { id: "vertical-push", name: "Vertical push", role: "secondary", required: true, movementPatternIds: ["vertical_push"], targetMuscleIds: ["shoulders"], matchPolicy: "any", variables: [v("exercise_selection"), v("sets"), v("repetitions")] },
    { id: "vertical-pull", name: "Vertical pull", role: "secondary", required: true, movementPatternIds: ["vertical_pull"], targetMuscleIds: ["latissimus_dorsi"], matchPolicy: "any", variables: [v("exercise_selection"), v("sets"), v("repetitions")] },
    { id: "arms", name: "Optional arm accessories", role: "accessory", required: false, movementPatternIds: ["elbow_flexion", "elbow_extension"], targetMuscleIds: ["biceps_brachii", "triceps_brachii"], matchPolicy: "any", variables: [v("exercise_selection"), v("sets"), v("repetitions")] },
  ] } } as SessionTemplate),
  builtin({ id: "builtin.basketball-practice", name: "Basketball High-intensity Practice", intent: "Develop technical decisions and repeated game-intensity efforts.", domain: "sport_skill", commonUseCases: ["Team practice", "Basketball conditioning"], notes: "Specific drills and durations are weekly variables.", structure: { kind: "sport_skill", blocks: [block("prep", "Movement preparation", "preparation", [v("duration")]), block("technical", "Technical skill", "technical", [v("drill"), v("duration"), v("intensity", false)]), block("small-sided", "Small-sided game", "small_sided_game", [v("participants"), v("duration"), v("intensity")]), block("tactical", "Tactical play", "tactical", [v("drill"), v("position", false), v("duration")]), block("cool-down", "Cooldown", "cool_down", [v("duration")])] } } as SessionTemplate),
  builtin({ id: "builtin.mobility-reset", name: "Mobility Reset", intent: "Support recovery through low-load movement and mobility.", domain: "recovery", commonUseCases: ["Recovery day", "Post-training reset"], notes: "Body regions and movements are selected for the current session.", structure: { kind: "recovery", blocks: [block("down-regulation", "Down-regulation", "down_regulation", [v("duration")]), block("mobility", "Mobility blocks", "mobility", [v("body_region"), v("movement"), v("duration")]), block("easy-movement", "Easy movement", "easy_movement", [v("movement"), v("duration"), v("intensity", false)])] } } as SessionTemplate),
  builtin({ id: "builtin.mind-body-reset", name: "Mind-body Reset", intent: "Practice attention, breathing and gentle integrated movement.", domain: "mind_body", commonUseCases: ["Low-load day", "Stress management"], notes: "Techniques and duration are selected per session.", structure: { kind: "mind_body", blocks: [block("centering", "Centering", "centering", [v("technique"), v("duration")]), block("practice", "Practice flow", "practice_flow", [v("technique"), v("duration"), v("intensity", false)]), block("breathing", "Breathing", "breathing", [v("technique"), v("duration")]), block("down-regulation", "Down-regulation", "down_regulation", [v("technique", false), v("duration")])] } } as SessionTemplate),
];

